### ISSUE TITLE
Comparison to CouchbaseLabs offering

### ISSUE THREAD

**Issue by adamski** [Upinion/react-native-couchbase-lite#10]
I have been using https://github.com/couchbaselabs/react-native-couchbase-lite however, feel that better efficiency might be achieved by not using the REST API. 

What are your motivations for writing this library, and can tell us key differences between it and the offering from CouchbaseLabs?

**Comment by juldiadia** [comment]
Hi, adamski

- When we started with this plugin that other plugin was still a WIP, also we didn't want a HTTP server running on our mobile phones. Those are the reasons why we started this plugin and we try to update it along with react-native.

- This plugin was written from scratch so, in terms of differences, it can be better or worse. We support native function to access couchbase but we haven't run any performance tests against them. As far as i can tell we are currently using this plugin in our app without problems.

I hope all your questions have been answered.
