### ISSUE TITLE
view returning whole doc, not respecting emit value

### ISSUE THREAD

**Issue by adamski** [Upinion/react-native-couchbase-lite#11]
I have a view function:

```js
function(doc) {
    emit (doc.name, doc.definition);
}
```

However, using the `getView` method, I get whole documents as the returned `value`. Is there something I'm missing, or is it something not supported here yet?

**Comment by juldiadia** [comment]
Hello, adamski.

`emit( key, value)`
- key is used as the row key for every row generated by the view.
- value is the value for every row generated by the view.

`getView` returns only the values, so actually the key in this case is only used for sorting the rows generated by the view.

If you want to have both I would suggest something like.
```
function(doc) {
    emit (doc.name, {name: doc.name, definition: doc.definition });
}
```

Hope it was helpful.

**Comment by adamski** [comment]
Thanks, I solved this by adding an "include_docs" parameter,
see https://github.com/adamski/react-native-couchbase/blob/8934957c21b62374a9e319b1fc4d5c4a0ffe6ac2/ios/RCTCouchBase/RCTCouchBase/RCTCouchBase.m#L926

BTW I have made many changes to my fork, let me know if you would like to merge some of them in. It would take quite a lot of time to separate them, I've added what I needed for an iOS project and will do the same for Android in the coming weeks.
