### ISSUE TITLE
Reduce function not working

### ISSUE THREAD

**Issue by adamski** [Upinion/react-native-couchbase-lite#13]
I'm tying to work out why my reduce function is not working. 
The same view code runs fine on Sync Gateway / CouchDB. 

Do you have an example of using a reduce function in a view using this library?

**Comment by juldiadia** [comment]
Hello, adamski.

I dont really know what is your problem with the reduce function, maybe some more information would be useful.

The reduce functions works with chunks, so you need to be aware of the rereduce param.

I'll paste an example in case is useful:
```
// Reducing a view with [key: 1, value: true, key: 2, value: false, ...]
function(keys, values, rereduce) {
    var stats = {
        'trues': 0,
        'falses': 0
    };
    for (var i = 0; i < values.length; i++) {
        if (!rereduce) {
            if (values[i]) {
                stats.trues++;
            } else {
                stats.falses++;
            }
        } else {
            stats.trues += values[i]['trues'];
            stats.falses += values[i]['falses'];
        }
    }
    return stats;
}
```

For more information https://wiki.apache.org/couchdb/Introduction_to_CouchDB_views#Reduce_Functions
