### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by npomfret** [Upinion/react-native-couchbase-lite#5]
Have you found that your react-native app loses its connection to the IOS listener when the phone goes to sleep?

**Comment by juldiadia** [comment]
Yes, the problem is that the listener is being deallocated from memory.

The solution for now is checking if the connection is still available or not, and restart it if it isn't.

For example:

``` javascript
//Use AppStateIOS for checking app state
 AppStateIOS.addEventListener('change', this.updateStatus);

function updateStatus(status) {
    if (status === 'active') {
        //Check status to listener with an info request for example
        fetch('http://localhost:port/localdatabase').then((response) => {
            if (!response.ok) throw 'No connection';
        }).catch(() => {
            //If the listener is off restart the connection, executing it again
            CouchBase.serverLocal(localport, userLocal, passwordLocal, (nport) => {
                //The new port for the listener should be the same, since the old listener wasn't working
                console.log(this.port === nport);
            });        
        });
    }
}
```

**Comment by juldiadia** [comment]
Well keep this issue opened till we find a better solution.

**Comment by npomfret** [comment]
Yeah, the listener dies.  I'm trying to fix the same issue on another project.  For now I've ended up using a similar solution.  My objective-c skills aren't up to much, but what I'd like to do is have my react-native iOS code automatically start the listener when it detects that the app has become active.
